### ISSUE TITLE
一款github转JsDelivr链接小工具

### ISSUE THREAD

**Issue by histion** [histion/blogfactory#17]
[cloud:nanami]: # 'https://yun.histion.cf/%E5%A4%87%E4%BB%BD%E5%9B%BE/pixiv/__original_drawn_by_anmi__36b11052924bd457b790157dffc449bd.png'

　　一款github转JsDelivr链接小工具，顺便加了刷新cdn

    因为老健忘症了，日常忘记github发布release后该怎么找到再js的cdn链接
    于是出现这个工具，贴入release链接自动转换成cdn链接*（请按格式贴入才行），并附带了刷新CDN的功能
    采用易语言编写，可能报毒…

> 本人比较低能，目前只会易语言OvO

----------
![预览](https://user-images.githubusercontent.com/65994410/108458579-eca4d200-72af-11eb-8a8b-e198b03220ec.png)

----------

github原地址：[求个star](https://github.com/histion/github-JsDelivr-tools "咕噜咕噜~")

在线下载：[下载链接](https://github.com/histion/github-JsDelivr-tools/releases/download/v0.11/github-JsDelivr.exe "点下去nya~")

**Comment by zhuziyi1989** [comment]
官方有工具呢～

https://www.jsdelivr.com/github
